## Devoir maison sur les élections présidentielles de 2022

Import des packages nécessaires et des données

In [12]:
import pandas as pd
!pip install great-tables
from great_tables import GT

df=pd.read_csv('https://www.data.gouv.fr/fr/datasets/r/182268fc-2103-4bcb-a850-6cf90b02a9eb')
df.head()

Requirement already satisfied: great-tables in /opt/python/lib/python3.13/site-packages (0.21.0)
Requirement already satisfied: commonmark>=0.9.1 in /opt/python/lib/python3.13/site-packages (from great-tables) (0.9.1)
Requirement already satisfied: faicons>=0.2.2 in /opt/python/lib/python3.13/site-packages (from great-tables) (0.2.2)
Requirement already satisfied: htmltools>=0.4.1 in /opt/python/lib/python3.13/site-packages (from great-tables) (0.6.0)
Requirement already satisfied: importlib-metadata in /opt/python/lib/python3.13/site-packages (from great-tables) (8.7.1)
Requirement already satisfied: typing_extensions>=3.10.0.0 in /opt/python/lib/python3.13/site-packages (from great-tables) (4.15.0)
Requirement already satisfied: Babel>=2.13.1 in /opt/python/lib/python3.13/site-packages (from great-tables) (2.18.0)
Requirement already satisfied: importlib-resources in /opt/python/lib/python3.13/site-packages (from great-tables) (6.5.2)
Requirement already satisfied: packaging>=20.9 in /opt/python/lib/python3.13/site-packages (from htmltools>=0.4.1->great-tables) (26.0)
Requirement already satisfied: zipp>=3.20 in /opt/python/lib/python3.13/site-packages (from importlib-metadata->great-tables) (3.23.0)

/tmp/ipykernel_9597/2401630193.py:5: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  df=pd.read_csv('https://www.data.gouv.fr/fr/datasets/r/182268fc-2103-4bcb-a850-6cf90b02a9eb')

,code_departement,libelle_departement,code_commune,libelle_commune,prenom,nom,voix
0,01,Ain,1,L'Abergement-Clémenciat,Nathalie,ARTHAUD,3
1,01,Ain,2,L'Abergement-de-Varey,Nathalie,ARTHAUD,2
2,01,Ain,4,Ambérieu-en-Bugey,Nathalie,ARTHAUD,38
3,01,Ain,5,Ambérieux-en-Dombes,Nathalie,ARTHAUD,8
4,01,Ain,6,Ambléon,Nathalie,ARTHAUD,0

### Question 1

In [16]:
#Première partie de la question
df=pd.read_csv('https://www.data.gouv.fr/fr/datasets/r/182268fc-2103-4bcb-a850-6cf90b02a9eb', low_memory=False)
df["code_commune"] = df["code_departement"].astype(str) + df["code_commune"].astype(str).str.zfill(3)

#df[df['libelle_commune'] == 'Montrouge']['code_commune'].values[0]

#Deucième partie de la question
df["candidat"] = df["prenom"] + " " + df["nom"]
df.head()

,code_departement,libelle_departement,code_commune,libelle_commune,prenom,nom,voix,candidat
0,01,Ain,01001,L'Abergement-Clémenciat,Nathalie,ARTHAUD,3,Nathalie ARTHAUD
1,01,Ain,01002,L'Abergement-de-Varey,Nathalie,ARTHAUD,2,Nathalie ARTHAUD
2,01,Ain,01004,Ambérieu-en-Bugey,Nathalie,ARTHAUD,38,Nathalie ARTHAUD
3,01,Ain,01005,Ambérieux-en-Dombes,Nathalie,ARTHAUD,8,Nathalie ARTHAUD
4,01,Ain,01006,Ambléon,Nathalie,ARTHAUD,0,Nathalie ARTHAUD

### Question 2

In [17]:
df_votes_exprimes = df[~df["candidat"].str.contains("BLANC|NUL|ABSTENTION", case=False, na=False)]

candidats = df_votes_exprimes["candidat"].nunique()

print(f"En 2022, il y avait {candidats} candidats à l'élection présidentielle.")

En 2022, il y avait 12 candidats à l'élection présidentielle.

### Question 3 (sans great_table, tableau avec un affichage print simple)

In [19]:
votes_nationaux = (
    df_votes_exprimes
    .groupby('candidat', as_index=False)['voix']
    .sum()
    .rename(columns={'voix': 'Nombre votes (total)'})
)

total_exprimes = votes_nationaux['Nombre votes (total)'].sum()

votes_nationaux['Score (% de votes exprimés)'] = (
    votes_nationaux['Nombre votes (total)'] / total_exprimes * 100
).round(2)

votes_nationaux = votes_nationaux.sort_values('Nombre votes (total)', ascending=False)

print(votes_nationaux.to_string(index=False))

             candidat  Nombre votes (total)  Score (% de votes exprimés)
      Emmanuel MACRON               9783058                        27.85
        Marine LE PEN               8133828                        23.15
   Jean-Luc MÉLENCHON               7712520                        21.95
         Éric ZEMMOUR               2485226                         7.07
     Valérie PÉCRESSE               1679001                         4.78
        Yannick JADOT               1627853                         4.63
        Jean LASSALLE               1101387                         3.13
       Fabien ROUSSEL                802422                         2.28
Nicolas DUPONT-AIGNAN                725176                         2.06
         Anne HIDALGO                616478                         1.75
      Philippe POUTOU                268904                         0.77
     Nathalie ARTHAUD                197094                         0.56

### Question 3 (avec great_tables)

In [21]:
table_votes_2022 = (
    GT(votes_nationaux)
    .tab_header(
        title=" Résultats du premier tour (2022)",
        subtitle="Scores nationaux des candidats à l'élection présidentielle"
    )
    .fmt_number(
        columns="Nombre votes (total)",
        decimals=0,
        use_seps=True,
        sep_mark=" "
    )
    .fmt_number(
        columns="Score (% de votes exprimés)",
        decimals=2
    )
    .cols_label(
        candidat="Candidat",
        **{
            "Nombre votes (total)": "Nombre de votes",
            "Score (% de votes exprimés)": "Score (%)"
        }
    )
)

table_votes_2022

GT(_tbl_data=                 candidat  Nombre votes (total)  Score (% de votes exprimés)
1         Emmanuel MACRON               9783058                        27.85
5           Marine LE PEN               8133828                        23.15
4      Jean-Luc MÉLENCHON               7712520                        21.95
11           Éric ZEMMOUR               2485226                         7.07
9        Valérie PÉCRESSE               1679001                         4.78
10          Yannick JADOT               1627853                         4.63
3           Jean LASSALLE               1101387                         3.13
2          Fabien ROUSSEL                802422                         2.28
7   Nicolas DUPONT-AIGNAN                725176                         2.06
0            Anne HIDALGO                616478                         1.75
8         Philippe POUTOU                268904                         0.77
6        Nathalie ARTHAUD                197094                         0.56, _body=<great_tables._gt_data.Body object at 0x7f4ec9c12fd0>, _boxhead=Boxhead([ColInfo(var='candidat', type=<ColInfoTypeEnum.default: 1>, column_label='Candidat', column_align='left', column_width=None), ColInfo(var='Nombre votes (total)', type=<ColInfoTypeEnum.default: 1>, column_label='Nombre de votes', column_align='right', column_width=None), ColInfo(var='Score (% de votes exprimés)', type=<ColInfoTypeEnum.default: 1>, column_label='Score (%)', column_align='right', column_width=None)]), _stub=<great_tables._gt_data.Stub object at 0x7f4e235c1bd0>, _spanners=Spanners([]), _heading=Heading(title=' Résultats du premier tour (2022)', subtitle="Scores nationaux des candidats à l'élection présidentielle", preheader=None), _stubhead=None, _summary_rows=<great_tables._gt_data.SummaryRows object at 0x7f4e235c1f90>, _summary_rows_grand=<great_tables._gt_data.SummaryRows object at 0x7f4ec9c12ea0>, _source_notes=[], _footnotes=[], _styles=[], _locale=<great_tables._gt_data.Locale object at 0x7f4e235c20d0>, _formats=[<great_tables._gt_data.FormatInfo object at 0x7f4e235c2490>, <great_tables._gt_data.FormatInfo object at 0x7f4ec9c12c40>], _substitutions=[], _col_merge=[], _options=Options(table_id=OptionsInfo(scss=False, category='table', type='value', value=None), table_caption=OptionsInfo(scss=False, category='table', type='value', value=None), table_width=OptionsInfo(scss=True, category='table', type='px', value='auto'), table_layout=OptionsInfo(scss=True, category='table', type='value', value='fixed'), table_margin_left=OptionsInfo(scss=True, category='table', type='px', value='auto'), table_margin_right=OptionsInfo(scss=True, category='table', type='px', value='auto'), table_background_color=OptionsInfo(scss=True, category='table', type='value', value='#FFFFFF'), table_additional_css=OptionsInfo(scss=False, category='table', type='values', value=[]), table_font_names=OptionsInfo(scss=False, category='table', type='values', value=['-apple-system', 'BlinkMacSystemFont', 'Segoe UI', 'Roboto', 'Oxygen', 'Ubuntu', 'Cantarell', 'Helvetica Neue', 'Fira Sans', 'Droid Sans', 'Arial', 'sans-serif']), table_font_size=OptionsInfo(scss=True, category='table', type='px', value='16px'), table_font_weight=OptionsInfo(scss=True, category='table', type='value', value='normal'), table_font_style=OptionsInfo(scss=True, category='table', type='value', value='normal'), table_font_color=OptionsInfo(scss=True, category='table', type='value', value='#333333'), table_font_color_light=OptionsInfo(scss=True, category='table', type='value', value='#FFFFFF'), table_border_top_include=OptionsInfo(scss=False, category='table', type='boolean', value=True), table_border_top_style=OptionsInfo(scss=True, category='table', type='value', value='solid'), table_border_top_width=OptionsInfo(scss=True, category='table', type='px', value='2px'), table_border_top_color=OptionsInfo(scss=True, category='table', type='value', value='#A8A8A8'), table_border_right_style=OptionsInfo(scss=True, category='table', type='value', value='none'), table_border_right_width=OptionsInfo(scss=True, category='table', type='px', value='2px'), table_border_right_color=OptionsInfo(scss=True, category='table', type='value', value='#D3D3D3'), table_border_bottom_include=OptionsInfo(scss=False, category='table', type='boolean', value=True), table_border_bottom_style=OptionsInfo(scss=True, category='table', type='value', value='solid'), table_border_bottom_width=OptionsInfo(scss=True, category='table', type='px', value='2px'), table_border_bottom_color=OptionsInfo(scss=True, category='table', type='value', value='#A8A8A8'), table_border_left_style=OptionsInfo(scss=True, category='table', type='value', value='none'), table_border_left_width=OptionsInfo(scss=True, category='table', type='px', value='2px'), table_border_left_color=OptionsInfo(scss=True, category='table', type='value', value='#D3D3D3'), heading_background_color=OptionsInfo(scss=True, category='heading', type='value', value=None), heading_align=OptionsInfo(scss=True, category='heading', type='value', value='center'), heading_title_font_size=OptionsInfo(scss=True, category='heading', type='px', value='125%'), heading_title_font_weight=OptionsInfo(scss=True, category='heading', type='value', value='initial'), heading_subtitle_font_size=OptionsInfo(scss=True, category='heading', type='px', value='85%'), heading_subtitle_font_weight=OptionsInfo(scss=True, category='heading', type='value', value='initial'), heading_padding=OptionsInfo(scss=True, category='heading', type='px', value='4px'), heading_padding_horizontal=OptionsInfo(scss=True, category='heading', type='px', value='5px'), heading_border_bottom_style=OptionsInfo(scss=True, category='heading', type='value', value='solid'), heading_border_bottom_width=OptionsInfo(scss=True, category='heading', type='px', value='2px'), heading_border_bottom_color=OptionsInfo(scss=True, category='heading', type='value', value='#D3D3D3'), heading_border_lr_style=OptionsInfo(scss=True, category='heading', type='value', value='none'), heading_border_lr_width=OptionsInfo(scss=True, category='heading', type='px', value='1px'), heading_border_lr_color=OptionsInfo(scss=True, category='heading', type='value', value='#D3D3D3'), column_labels_background_color=OptionsInfo(scss=True, category='column_labels', type='value', value=None), column_labels_font_size=OptionsInfo(scss=True, category='column_labels', type='px', value='100%'), column_labels_font_weight=OptionsInfo(scss=True, category='column_labels', type='value', value='normal'), column_labels_text_transform=OptionsInfo(scss=True, category='column_labels', type='value', value='inherit'), column_labels_padding=OptionsInfo(scss=True, category='column_labels', type='px', value='5px'), column_labels_padding_horizontal=OptionsInfo(scss=True, category='column_labels', type='px', value='5px'), column_labels_vlines_style=OptionsInfo(scss=True, category='table_body', type='value', value='none'), column_labels_vlines_width=OptionsInfo(scss=True, category='table_body', type='px', value='1px'), column_labels_vlines_color=OptionsInfo(scss=True, category='table_body', type='value', value='#D3D3D3'), column_labels_border_top_style=OptionsInfo(scss=True, category='column_labels', type='value', value='solid'), column_labels_border_top_width=OptionsInfo(scss=True, category='column_labels', type='px', value='2px'), column_labels_border_top_color=OptionsInfo(scss=True, category='column_labels', type='value', value='#D3D3D3'), column_labels_border_bottom_style=OptionsInfo(scss=True, category='column_labels', type='value', value='solid'), column_labels_border_bottom_width=OptionsInfo(scss=True, category='column_labels', type='px', value='2px'), column_labels_border_bottom_color=OptionsInfo(scss=True, category='column_labels', type='value', value='#D3D3D3'), column_labels_border_lr_style=OptionsInfo(scss=True, category='column_labels', type='value', value='none'), column_labels_border_lr_width=OptionsInfo(scss=True, category='column_labels', type='px', value='1px'), column_labels_border_lr_color=OptionsInfo(scss=True, category='column_labels', type='value', value='#D3D3D3'), column_labels_hidden=OptionsInfo(scss=False, category='column_labels', type='boolean', value=False), row_group_background_color=OptionsInfo(scss=True, category='row_group', type='value', value=None), row_group_font_size=OptionsInfo(scss=True, category='row_group', type='px', value='100%'), row_group_font_weight=OptionsInfo(scss=True, category='row_group', type='value', value='initial'), row_group_text_transform=OptionsInfo(scss=True, category='row_group', type='value', value='inherit'), row_group_padding=OptionsInfo(scss=True, category='row_group', type='px', value='8px'), row_group_padding_horizontal=OptionsInfo(scss=True, category='row_group', type='px', value='5px'), row_group_border_top_style=OptionsInfo(scss=True, category='row_group', type='value', value='solid'), row_group_border_top_width=OptionsInfo(scss=True, category='row_group', type='px', value='2px'), row_group_border_top_color=OptionsInfo(scss=True, category='row_group', type='value', value='#D3D3D3'), row_group_border_right_style=OptionsInfo(scss=True, category='row_group', type='value', value='none'), row_group_border_right_width=OptionsInfo(scss=True, category='row_group', type='px', value='1px'), row_group_border_right_color=OptionsInfo(scss=True, category='row_group', type='value', value='#D3D3D3'), row_group_border_bottom_style=OptionsInfo(scss=True, category='row_group', type='value', value='solid'), row_group_border_bottom_width=OptionsInfo(scss=True, category='row_group', type='px', value='2px'), row_group_border_bottom_color=OptionsInfo(scss=True, category='row_group', type='value', value='#D3D3D3'), row_group_border_left_style=OptionsInfo(scss=True, category='row_group', type='value', value='none'), row_group_border_left_width=OptionsInfo(scss=True, category='row_group', type='px', value='1px'), row_group_border_left_color=OptionsInfo(scss=True, category='row_group', type='value', value='#D3D3D3'), row_group_as_column=OptionsInfo(scss=False, category='row_group', type='boolean', value=False), table_body_hlines_style=OptionsInfo(scss=True, category='table_body', type='value', value='solid'), table_body_hlines_width=OptionsInfo(scss=True, category='table_body', type='px', value='1px'), table_body_hlines_color=OptionsInfo(scss=True, category='table_body', type='value', value='#D3D3D3'), table_body_vlines_style=OptionsInfo(scss=True, category='table_body', type='value', value='none'), table_body_vlines_width=OptionsInfo(scss=True, category='table_body', type='px', value='1px'), table_body_vlines_color=OptionsInfo(scss=True, category='table_body', type='value', value='#D3D3D3'), table_body_border_top_style=OptionsInfo(scss=True, category='table_body', type='value', value='solid'), table_body_border_top_width=OptionsInfo(scss=True, category='table_body', type='px', value='2px'), table_body_border_top_color=OptionsInfo(scss=True, category='table_body', type='value', value='#D3D3D3'), table_body_border_bottom_style=OptionsInfo(scss=True, category='table_body', type='value', value='solid'), table_body_border_bottom_width=OptionsInfo(scss=True, category='table_body', type='px', value='2px'), table_body_border_bottom_color=OptionsInfo(scss=True, category='table_body', type='value', value='#D3D3D3'), data_row_padding=OptionsInfo(scss=True, category='data_row', type='px', value='8px'), data_row_padding_horizontal=OptionsInfo(scss=True, category='data_row', type='px', value='5px'), stub_background_color=OptionsInfo(scss=True, category='stub', type='value', value=None), stub_font_size=OptionsInfo(scss=True, category='stub', type='px', value='100%'), stub_font_weight=OptionsInfo(scss=True, category='stub', type='value', value='initial'), stub_text_transform=OptionsInfo(scss=True, category='stub', type='value', value='inherit'), stub_border_style=OptionsInfo(scss=True, category='stub', type='value', value='solid'), stub_border_width=OptionsInfo(scss=True, category='stub', type='px', value='2px'), stub_border_color=OptionsInfo(scss=True, category='stub', type='value', value='#D3D3D3'), stub_row_group_background_color=OptionsInfo(scss=True, category='stub', type='value', value=None), stub_row_group_font_size=OptionsInfo(scss=True, category='stub', type='px', value='100%'), stub_row_group_font_weight=OptionsInfo(scss=True, category='stub', type='value', value='initial'), stub_row_group_text_transform=OptionsInfo(scss=True, category='stub', type='value', value='inherit'), stub_row_group_border_style=OptionsInfo(scss=True, category='stub', type='value', value='solid'), stub_row_group_border_width=OptionsInfo(scss=True, category='stub', type='px', value='2px'), stub_row_group_border_color=OptionsInfo(scss=True, category='stub', type='value', value='#D3D3D3'), grand_summary_row_padding=OptionsInfo(scss=True, category='grand_summary_row', type='px', value='8px'), grand_summary_row_padding_horizontal=OptionsInfo(scss=True, category='grand_summary_row', type='px', value='5px'), grand_summary_row_background_color=OptionsInfo(scss=True, category='grand_summary_row', type='value', value=None), grand_summary_row_text_transform=OptionsInfo(scss=True, category='grand_summary_row', type='value', value='inherit'), grand_summary_row_border_style=OptionsInfo(scss=True, category='grand_summary_row', type='value', value='double'), grand_summary_row_border_width=OptionsInfo(scss=True, category='grand_summary_row', type='px', value='6px'), grand_summary_row_border_color=OptionsInfo(scss=True, category='grand_summary_row', type='value', value='#D3D3D3'), source_notes_padding=OptionsInfo(scss=True, category='source_notes', type='px', value='4px'), source_notes_padding_horizontal=OptionsInfo(scss=True, category='source_notes', type='px', value='5px'), source_notes_background_color=OptionsInfo(scss=True, category='source_notes', type='value', value=None), source_notes_font_size=OptionsInfo(scss=True, category='source_notes', type='px', value='90%'), source_notes_border_bottom_style=OptionsInfo(scss=True, category='source_notes', type='value', value='none'), source_notes_border_bottom_width=OptionsInfo(scss=True, category='source_notes', type='px', value='2px'), source_notes_border_bottom_color=OptionsInfo(scss=True, category='source_notes', type='value', value='#D3D3D3'), source_notes_border_lr_style=OptionsInfo(scss=True, category='source_notes', type='value', value='none'), source_notes_border_lr_width=OptionsInfo(scss=True, category='source_notes', type='px', value='2px'), source_notes_border_lr_color=OptionsInfo(scss=True, category='source_notes', type='value', value='#D3D3D3'), source_notes_multiline=OptionsInfo(scss=False, category='source_notes', type='boolean', value=True), source_notes_sep=OptionsInfo(scss=False, category='source_notes', type='value', value=' '), row_striping_background_color=OptionsInfo(scss=True, category='row', type='value', value='#F4F4F4'), row_striping_include_stub=OptionsInfo(scss=False, category='row', type='boolean', value=False), row_striping_include_table_body=OptionsInfo(scss=False, category='row', type='boolean', value=False), container_width=OptionsInfo(scss=False, category='container', type='px', value='auto'), container_height=OptionsInfo(scss=False, category='container', type='px', value='auto'), container_padding_x=OptionsInfo(scss=False, category='container', type='px', value='0px'), container_padding_y=OptionsInfo(scss=False, category='container', type='px', value='10px'), container_overflow_x=OptionsInfo(scss=False, category='container', type='overflow', value='auto'), container_overflow_y=OptionsInfo(scss=False, category='container', type='overflow', value='auto'), quarto_disable_processing=OptionsInfo(scss=False, category='quarto', type='logical', value=False), quarto_use_bootstrap=OptionsInfo(scss=False, category='quarto', type='logical', value=False)), _google_font_imports=GoogleFontImports(imports=frozenset()), _has_built=False)

### Question 4

In [70]:
score_departements = df_votes_exprimes.groupby(
    ["code_departement", "candidat"])["voix"].sum().reset_index()
total_dep = score_departements.groupby("code_departement")["voix"].sum().reset_index()
total_dep = total_dep.rename(columns={"voix": "total_dep"})
score_departements = score_departements.merge(total_dep, on="code_departement")
score_departements["score"] = (score_departements["voix"] / score_departements["total_dep"] * 100 ).round(2)
score_departements = score_departements.drop(columns="total_dep")
score_departements = score_departements.sort_values(["voix", "score"], ascending=False)
score_departements["score"] = score_departements["score"].astype(str) + " %"
score_departements

     code_departement            candidat    voix    score
713                59       Marine LE PEN  373127  29.27 %
901                75     Emmanuel MACRON  372820  35.34 %
709                59     Emmanuel MACRON  336138  26.37 %
904                75  Jean-Luc MÉLENCHON  317372  30.08 %
749                62       Marine LE PEN  305816  38.68 %
...               ...                 ...     ...      ...
1232              977     Philippe POUTOU      27   1.02 %
1206              975    Nathalie ARTHAUD      22   0.81 %
1202              975      Fabien ROUSSEL      19    0.7 %
1226              977      Fabien ROUSSEL      14   0.53 %
1230              977    Nathalie ARTHAUD      10   0.38 %

[1296 rows x 4 columns]

In [71]:
#Vérification pour l'Aude
score_departements[score_departements["code_departement"] == "11"]

    code_departement               candidat   voix    score
125               11          Marine LE PEN  64027  30.14 %
121               11        Emmanuel MACRON  43104  20.29 %
124               11     Jean-Luc MÉLENCHON  42039  19.79 %
131               11           Éric ZEMMOUR  18434   8.68 %
123               11          Jean LASSALLE  12382   5.83 %
129               11       Valérie PÉCRESSE   7350   3.46 %
130               11          Yannick JADOT   6322   2.98 %
120               11           Anne HIDALGO   6166    2.9 %
122               11         Fabien ROUSSEL   5622   2.65 %
127               11  Nicolas DUPONT-AIGNAN   4206   1.98 %
128               11        Philippe POUTOU   1748   0.82 %
126               11       Nathalie ARTHAUD   1026   0.48 %

### Question 5

In [72]:
votes_france_entiere = votes_nationaux.rename(columns={
    "voix": "Nombre votes (total)",
    "score": "Score (% de votes exprimés)"
})

score_departements = score_departements.merge(
    votes_nationaux[["candidat", "Nombre votes (total)", "Score (% de votes exprimés)"]].rename(columns={
        "Nombre votes (total)": "votes_national",
        "Score (% de votes exprimés)": "score_national"
    }),
    on="candidat"
)
score_departements["score_national"] = score_departements["score_national"] .astype(str) + " %"
score_departements

,code_departement,candidat,voix,score,votes_national,score_national
0,59,Marine LE PEN,373127,29.27 %,8133828,23.15 %
1,75,Emmanuel MACRON,372820,35.34 %,9783058,27.85 %
2,59,Emmanuel MACRON,336138,26.37 %,9783058,27.85 %
3,75,Jean-Luc MÉLENCHON,317372,30.08 %,7712520,21.95 %
4,62,Marine LE PEN,305816,38.68 %,8133828,23.15 %
...,...,...,...,...,...,...
1291,977,Philippe POUTOU,27,1.02 %,268904,0.77 %
1292,975,Nathalie ARTHAUD,22,0.81 %,197094,0.56 %
1293,975,Fabien ROUSSEL,19,0.7 %,802422,2.28 %
1294,977,Fabien ROUSSEL,14,0.53 %,802422,2.28 %
1295,977,Nathalie ARTHAUD,10,0.38 %,197094,0.56 %

In [64]:
#Vérification pour l'Aude
score_departements[score_departements["code_departement"] == "11"]

,code_departement,candidat,voix,score,votes_national,score_national
162,11,Marine LE PEN,64027,30.14 %,8133828,23.15
234,11,Emmanuel MACRON,43104,20.29 %,9783058,27.85
245,11,Jean-Luc MÉLENCHON,42039,19.79 %,7712520,21.95
414,11,Éric ZEMMOUR,18434,8.68 %,2485226,7.07
541,11,Jean LASSALLE,12382,5.83 %,1101387,3.13
726,11,Valérie PÉCRESSE,7350,3.46 %,1679001,4.78
770,11,Yannick JADOT,6322,2.98 %,1627853,4.63
777,11,Anne HIDALGO,6166,2.9 %,616478,1.75
812,11,Fabien ROUSSEL,5622,2.65 %,802422,2.28
901,11,Nicolas DUPONT-AIGNAN,4206,1.98 %,725176,2.06
1114,11,Philippe POUTOU,1748,0.82 %,268904,0.77
1184,11,Nathalie ARTHAUD,1026,0.48 %,197094,0.56

### Question 6

In [76]:
score_departements["surrepresentation"] = (
    (score_departements["score"].str.replace(" %", "").astype(float)
     - score_departements["score_national"] .str.replace(" %", "").astype(float))
    / score_departements["score_national"] .str.replace(" %", "").astype(float) * 100
).round(2)

score_departements["surrepresentation"] = score_departements["surrepresentation"].astype(str) + " (%)"

score_departements

,code_departement,candidat,voix,score,votes_national,score_national,surrepresentation
0,59,Marine LE PEN,373127,29.27 %,8133828,23.15 %,26.44 (%)
1,75,Emmanuel MACRON,372820,35.34 %,9783058,27.85 %,26.89 (%)
2,59,Emmanuel MACRON,336138,26.37 %,9783058,27.85 %,-5.31 (%)
3,75,Jean-Luc MÉLENCHON,317372,30.08 %,7712520,21.95 %,37.04 (%)
4,62,Marine LE PEN,305816,38.68 %,8133828,23.15 %,67.08 (%)
...,...,...,...,...,...,...,...
1291,977,Philippe POUTOU,27,1.02 %,268904,0.77 %,32.47 (%)
1292,975,Nathalie ARTHAUD,22,0.81 %,197094,0.56 %,44.64 (%)
1293,975,Fabien ROUSSEL,19,0.7 %,802422,2.28 %,-69.3 (%)
1294,977,Fabien ROUSSEL,14,0.53 %,802422,2.28 %,-76.75 (%)
1295,977,Nathalie ARTHAUD,10,0.38 %,197094,0.56 %,-32.14 (%)